- hosts: proxy
  become: yes
  become_user: root
  vars_files:
    ./vars/nginx.yml
  tasks:
    - name: install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: ['docker.io', 'python3-pip']
    - name: Install Docker Module for Python
      pip:
        name: docker
    - name: create conf directory
      file:
        path: /etc/nginx/conf.d
        state: directory
    - name: copy configs
      template:
        src: ./files/nginx/conf.d/{{ item }}
        dest: /etc/nginx/conf.d/{{ item }}
      with_items:
        - mshatunov-dev.conf
    - name: create cert directory
      file:
        path: /etc/nginx/cert
        state: directory
    - name: copy certs
      template:
        src: ./files/nginx/cert/{{ item }}
        dest: /etc/nginx/cert/{{ item }}
      with_items:
        - privkey-dev.pem
        - fullchain-dev.pem
    - name: start nginx container
      docker_container:
        name: nginx
        image: nginx:{{ nginx_version }}
        state: started
        restart: yes
        volumes:
          - /etc/nginx/conf.d:/etc/nginx/conf.d:ro
          - /etc/nginx/cert:/etc/nginx/cert/:ro
        ports:
          - "80:80"
          - "443:443"